---
title: "Wisdom of Crowds?"
author: "Homer White"
date: "1/28/2020"
output:
  rmdformats::readthedown:
    highlight: kate
    toc_depth: 2
runtime: shiny
---

```{r setup, include=FALSE}
library(shinyjs)
library(ggrepel)
source("globals.R")
load("data/results_3_36_200_1to20_3030.rda")
knitr::opts_chunk$set(echo = FALSE)
```


## Solving

Some text here.

```{r solving_code}
## solving ui ----
fluidRow(
  useShinyjs(rmd = TRUE),
  column(
    width = 6,
    wellPanel(
       textInput(
      inputId = "solving_heuristic",
      label = "Solver Moves (separate by commas)",
      value = "1,10,20"
    ),
    numericInput(
      inputId = "solving_smoothing_factor",
      label = "Smoothing Factor",
      value = 10,
      min = 1,
      max = settings$max_smoothness
    )
    )
   
  ),
  column(
    width = 6,
    wellPanel(
      actionButton(
      inputId = "solving_make_landscape",
      label = HTML("Make New <br>Landscape")
    ),
     br(), br(),
  hidden(
    actionButton(
      inputId = "solving_move",
      label = HTML("Try Another<br>Option")
    )
  ) # end hidden
  )
 
    )
    
)

hidden(div(
  id = "solving_outputs",
  fluidRow(
  column(
    width = 9,
    plotOutput("solving_landscape_plot")
  ),
  column(
    width = 3,
    tableOutput("solving_process")
  )
)
))


## solving reactive values ----
rv_solving <- reactiveValues(
  landscape = NULL,
  solving = FALSE,
  moved = NA,
  current = 1,
  possibility = 1,
  best = 0,
  strikes = 0,
  steps = 0,
  simulations = NULL,
  team_results = NULL
)

## solving observers ----
observeEvent(input$solving_make_landscape, {
  rv_solving$landscape <-
    make_landscape(
      n = settings$options,
      smoothing_factor = input$solving_smoothing_factor,
      max_value = settings$max_value
    )
  rv_solving$current <- 1
  rv_solving$best <- 0
  rv_solving$strikes <- 0
  rv_solving$steps <- 0
  rv_solving$solving <- TRUE
  rv_solving$moved <- NA
  rv_solving$possibility <- 1
  show("solving_move")
  show("solving_outputs")
})

observeEvent(input$solving_move, {
  current <- rv_solving$current
  strikes <- rv_solving$strikes
  steps <- rv_solving$steps
  best <- rv_solving$best
  landscape <- rv_solving$landscape
  heuristic <- str_split(
    input$solving_heuristic,
    pattern = ",\\s*"
  ) %>%
    unlist() %>%
    as.numeric()
  h_length <- length(heuristic)
  try <- steps %% h_length + 1
  rv_solving$moved <- heuristic[try]
  possibility <- ifelse(
    (current + heuristic[try]) %% length(landscape) == 0,
    length(landscape),
    (current + heuristic[try]) %% length(landscape)
  )
  rv_solving$possibility <- possibility
  if (landscape[possibility] > best) {
    rv_solving$current <- possibility
    rv_solving$best <- landscape[possibility]
    rv_solving$strikes <- 0
  } else {
    rv_solving$strikes <- strikes + 1
  }
  rv_solving$steps <- steps + 1
  if (rv_solving$strikes == h_length) {
    rv_solving$solving <- FALSE
    hide("solving_move")
  }
})

## solving outputs ----
output$solving_landscape_plot <- renderPlot({
  if (!is.null(rv_solving$landscape)) {
    landscape <- rv_solving$landscape
    df <- data.frame(
      approach = 1:length(landscape),
      value = landscape
    )
    present <- data.frame(
      x = c(rv_solving$current, rv_solving$possibility),
      y = c(
        landscape[rv_solving$current],
        landscape[rv_solving$possibility]
      ),
      point = c("current best", "trying")
    )
    p <-
      ggplot(df, aes(x = approach, y = value)) +
      geom_line() +
      geom_point(
        data = present,
        aes(
          x = x, y = y,
          color = point
        ),
        size = 3
      ) +
      scale_color_manual(values = c("blue", "red")) +
      geom_label_repel(
        data = present,
        mapping = aes(x = x, y = y, label = point),
        force = 10
      ) +
      theme(legend.position = "none")
    print(p)
  }
})

output$solving_process <- renderTable(
  {
    rv_solving$steps
    if (!is.null(rv_solving$landscape)) {
      results <- c(
        moved = as.character(isolate(rv_solving$moved)),
        trying = as.character(isolate(rv_solving$possibility)),
        `best so far` = as.character(round(isolate(rv_solving$best), 3)),
        strikes = as.character(isolate(as.integer(rv_solving$strikes))),
        stuck = as.character(!isolate(rv_solving$solving))
      )
      result_names <- c(
        "moved", "trying", "best so far", "strikes", "stuck?"
      )
      df <- data.frame(results)
      names(df) <- ""
      row.names(df) <- result_names
      df
    }
  },
  rownames = TRUE
)
```


And more text!


## Ability

Still more text.

```{r ability_code}
## ability ui ----
fluidRow(
  column(
    width = 6,
    wellPanel(
      textInput(
      inputId = "ability_heuristic",
      label = "Solver Moves (separate by commas)",
      value = "1,10,20"
    ),
    numericInput(
      inputId = "ability_smoothing_factor",
      label = "Smoothing Factor",
      value = 10,
      min = 1,
      max = settings$max_smoothness
    )
    )
    
  ),
  column(
    width = 6,
    wellPanel(
       numericInput(
      inputId = "ability_sims",
      label = HTML("Number of<br>Simulations<br>(max 100000)"),
      value = 1000,
      min = 1,
      max = 100000
    ),
    br(), br(),
    actionButton(
      inputId = "ability_go",
      label = HTML("Simulate")
    )
    )
   
  )
)

fluidRow(
  column(
    width = 3,
    tableOutput("ability_simresults")
  ),
  column(
    width = 9,
    plotOutput("ability_simsplot")
  )
)


## ability reactive values ----

rv_ability <- reactiveValues(
  simulations = NULL
)

## ability observers ----

observeEvent(input$ability_go, {
  reps <- input$ability_sims
  simulations <- numeric(reps)
  heuristic <- str_split(
    input$ability_heuristic,
    pattern = ",\\s*"
  ) %>%
    unlist() %>%
    as.numeric()
  withProgress(
    message = "Simulating ...",
    min = 1,
    max = input$ability_sims,
    {
      for (i in 1:reps) {
        landscape <- make_landscape(
          n = settings$options,
          smoothing_factor = input$ability_smoothing_factor,
          max_value = settings$max_value
        )
        simulations[i] <- solve_landscape(
          heuristic = heuristic,
          landscape = landscape
        )$val
        incProgress(1 / reps * 100, detail = paste(ceiling(i / reps * 100), "% done"))
      }
    }
  )

  rv_ability$simulations <- simulations
})


## ability outputs ----

output$ability_simsplot <- renderPlot({
  if (!is.null(rv_ability$simulations)) {
    data.frame(value = rv_ability$simulations) %>%
      ggplot(aes(x = value)) +
      geom_density(fill = "burlywood") +
      geom_rug() +
      labs(x = "value at stopping solution")
  }
})

output$ability_simresults <- renderTable(
  {
    if (!is.null(rv_ability$simulations)) {
      sims <- round(rv_ability$simulations, 3)
      results <- c(
        as.character(min(sims)),
        as.character(median(sims)),
        as.character(mean(sims)),
        as.character(max(sims))
      )
      result_names <- c(
        "minimum", "median", "mean", "maximum"
      )
      df <- data.frame(results)
      names(df) <- ""
      row.names(df) <- result_names
      df
    }
  },
  rownames = TRUE
)
```



And even more ...

## Teams

More text.

```{r teams_code}
## teams ui ----
      fluidRow(
        column(width = 3,
        wellPanel(
            numericInput(inputId = "teams_expert_size", label = "Expert Team Size",
                         min = 1, value = 6, step = 1),
            numericInput(inputId = "teams_random_size", label = "Random Team Size",
                         min = 1, value = 6, step = 1)
          )),
        column(width = 6,
        wellPanel(
          sliderInput(
              inputId = "teams_move_limit",
              label = "Maximum Heuristic",
              value = 12,
              min = 1, max = 36,
              step = 1
            ),
            sliderInput(
              inputId = "teams_sf_range",
              label = "Smoothing-Factor Range",
              value = c(1, 20),
              min = 1, max = 20,
              step = 1
            ))),
        column(width = 3,
          wellPanel(
            numericInput(
            inputId = "teams_sims",
            label = HTML("Number of<br>Simulations<br>(max 10000)"),
            value = 1000,
            min = 1,
            max = 10000
          ),
          actionButton(
            inputId = "teams_simulate",
            label = "Simulate"
          )
          ))
      )

hidden(
  div(
    id = "teams_outputs",
    fluidRow(
  plotOutput("teams_plot")
)
  )
)


## teams reactive values ----

rv_teams <- reactiveValues(
  simulations = NULL,
  results = NULL
)

## teams observers ----

observeEvent(input$teams_simulate, {
  show("teams_outputs")
    lst <- get_bounded_all(bound = input$teams_move_limit, 
                           lst = results_3_36_200_1to20_3030)
    lower <- isolate(input$teams_sf_range[1])
    upper <- isolate(input$teams_sf_range[2])
    rv_teams$results <- withProgress(
      message = "Simulating ...", 
      min = lower, max = upper, 
      comparison(
        sims = input$teams_sims,
        seed = NULL,
        expert_size = input$teams_expert_size,
        expert_limit = input$teams_expert_size,
        random_size = input$teams_random_size,
        set = lst)
      )
  })



## teams outputs ----
 output$teams_plot <- renderPlot({
    if (!is.null(rv_teams$results)) {
      lower <- isolate(input$teams_sf_range[1])
      upper <- isolate(input$teams_sf_range[2])
      sims <- isolate(input$teams_sims)
      ggplot(rv_teams$results, aes(x = factor, y = mean_diff)) +
        geom_ribbon(aes(ymin = mean_diff - 2 * sd_diff/sqrt(sims), 
                        ymax = mean_diff + 2 * sd_diff/sqrt(sims)),
                    fill = "grey70", alpha = 0.5) +
        geom_line(aes(y = mean_diff)) +
        geom_hline(yintercept = 0) +
        scale_x_continuous(breaks = lower:upper) +
        labs(x = "smoothing factor",
             y = "mean of differences (experts - randoms)",
             title = "Mean Difference in Score (Expert - Random) vs. Smoothing-Factor")
    }
  })

```




